# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b7de4d766076851e1159f7affd06b81f378aed2740705d5f5ef95335cc6ef68ea9211f205ac389c9189d363412ddaad730dfc874af2cf2f07fb971e05c5c0b0

test:
  secret_key_base: 1362446c4c21eb6c3cd9a4a20ea1b76c0c394fa2a0e0bac2262043f62ad8f22f1533c22117421cb5fbdfa3b724cd80a649d50f8f8bcba75341e435be582ea108

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
